#!/bin/bash

set -e
#set -u

action="$1"

if [ "$action" != configure ]
  then
  exit 0
fi

move_squid3_logrotate()
{
    # FIXME: Not the best way to handle this but no alernatives that aren't messy
    mv -f /etc/logrotate.d/squid3 /etc/logrotate.d/squid3.disabled || true
}

move_squid3_logrotate

#DEBHELPER#

# Wait for squid to finish restarting
sleep 2

if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d squid3 restart || true
else
       /etc/init.d/squid3 restart || true
fi

